name: Deploy Docs

on:
    workflow_dispatch:

jobs:
    deploy-nightly-demo-app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: yarn install
            - run: npm run build
              working-directory: packages/dockview-core
            - run: npm run build
              working-directory: packages/dockview
            - run: npm run build
              working-directory: packages/dockview-vue
            - run: npm run build
              working-directory: packages/dockview-react
            - run: npm run build
              working-directory: packages/dockview-angular
            - run: npm run build
              working-directory: packages/docs
            - run: npm run docs
              working-directory: .
            - run: node scripts/package-docs.js
              working-directory: .
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: build # The folder the action should deploy.
                  TARGET_FOLDER: .
                  CLEAN: true # Automatically remove deleted files from the deploy branch
